### ISSUE TITLE
Basic Implementation of CH4 and N2O

### ISSUE THREAD

**Issue by njleach** [OMS-NetZero/FAIR-pro#7]
Seems to make sense to add both of these at the same time as they are dependent on one another. By "basic", I mean fixed lifetimes for both, all equations and data will be taken from IPCC, mainly from AR5 8.SM. My plan is to do them in as similar a manner as to how Carbon is currently implemented to make the whole code as clear as possible. I'll work in the branch FAIR-pro/FAIR-basic-development/Additional_GHG_Implementation, and will comment fairly exhaustively as I code.

- [x] Add in all additional parameters to the definition required: M_emissions, N_emissions, M_concs, N_concs, M_life, N_life, M_0, N_0. There may be some unit conversions needed (such as ppm_gtc, but I'll add these as necessary).

- [x] Add a check to see if M and/or N emissions are supplied- if not then don't output M and/or N concentrations as the end.

- [x] Add in checks for CH4 and N2O being emissions or concentrations driven (I'm a little wary as this will likely lengthen the program by quite a bit, however, I'll try and be as concise as possible). _I think I'll start by requiring the program is either entirely concentrations driven or entirely emissions driven, with it being set by the CO2 arguments, otherwise it will end up very long. I'll raise an error if concentrations are supplied for some gases and emissions for others._

- [x] Add in a check that all the emissions or concentrations timeseries are the same length, raise error if not.

- [x] Create np.zeros in which CH4 and N2O concentrations will be stored, I'll call these M and N for simplicity.

- [x] Add lines to compute the first timestep concentrations, based on emissions or concentrations, in a manner very similar to CO2.

- [x] Add in two extra definitions that just contain the equations for RF due to CH4 and N2O- I feel this should make the code clearer than just adding them to the RF line since they are both pretty long.

- [x] Add the relevant terms to the RF (in both first ts and rest of run).

- [x] Add in lines to compute the M and N concentrations for the rest of the run, these will be virtually identical to the CO2 line, except with different time constants and only one reservoir vs. 4.

FAIR should now calculate the temperature including the other gases- no alterations need to be made to the temperature calculations I think.

- [x] Add M and N concentrations as outputs.

**Comment by znicholls** [comment]
Looks great. The only suggestion I'd make is that to maintain some semblance of backwards compatibility you only return M and N if M and N emissions/concentrations were supplied as inputs?

**Comment by njleach** [comment]
Yes, that's a good point, I'll make sure that happens when I get there.
