### ISSUE TITLE
Implementation of CFCs/HCFCs

### ISSUE THREAD

**Issue by njleach** [OMS-NetZero/FAIR-pro#9]
Currently planning on adding in a term in the RF lines which I'll comment is due to these, and a TRUE/FALSE parameter so the user can specify whether they want to include these or not. I think that just adding in a RF using IPCC data (Montreal gases, IPCC AR5 table 8.2) is best for now to avoid the code getting overly complicated, but can think about whether a more detailed implementation is possible later.

**Comment by njleach** [comment]
There was a thought from Richard that maybe we could include CFC's and HFC's by defining a function that works by modelling all the other CFCs/HCFCs in the same way- with a fixed lifetime, and by getting coefficient values for their radiative forcing from the literature. Suggested inputs would be the names of all the CFCs/HFCs that are wanted to be included. Will have a think about how to include these in a way that doesn't lengthen the code significantly, and expect I won't get the program to output their concentrations.

**Comment by znicholls** [comment]
@njleach @richardcode 
Sorry I haven't looked at the code in any detail but just want to make sure we're being careful to make clear where each of the different forcings go e.g. how does `external_forcing` differ from `co2_forcing` and if we don't have say CH_4 emissions then is CH_4 forcing included in `external_forcing` or should it be read into a different variable?
